# Generated by Django 4.2.25 on 2025-10-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_phone_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_verified",
        ),
    ]
