# Generated by hand: add description and brochure to Course
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_college_latitude_college_longitude_college_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='brochure',
            field=models.FileField(upload_to='course_brochures/', null=True, blank=True),
        ),
    ]
