# Generated by Django 4.2.25 on 2025-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_job_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
