# Generated by Django 4.2.25 on 2025-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_job_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertifiedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("ppt_file", models.FileField(upload_to="courses/ppt/")),
                ("post_image", models.ImageField(upload_to="courses/images/")),
            ],
        ),
        migrations.CreateModel(
            name="JobInCareer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("job_image", models.ImageField(upload_to="jobs/images/")),
            ],
        ),
        migrations.AddField(
            model_name="college",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="college_backgrounds/"
            ),
        ),
    ]
