# Generated by Django 4.2.25 on 2025-11-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_aboutpage_director_staffmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
